### PR TITLE
Bump Pylint to 2.17

### PR DESCRIPTION
**Pull request by bebound**
Bump pylint to support Python 3.11.

`pylint==2.11.1` breaks `vcrpy`, as `wrapt` 1.13 does not support 3.11.
`wrapt` support 3.11 in 1.14 https://wrapt.readthedocs.io/en/latest/changes.html#version-1-14-0

```
├── pylint==2.11.1                                                                                  python code static checker
│   ├── astroid<2.9,>=2.8.0                                                                         An abstract syntax tree for Python with inference support.
│   │   ├── lazy-object-proxy>=1.4.0                                                                A fast and thorough lazy object proxy.
│   │   ├── setuptools>=20.0                                                                        Easily download, build, install, upgrade, and uninstall Python packages
│   │   └── wrapt<1.14,>=1.11
```
Related issue: https://github.com/Azure/azure-cli/issues/24494

This also makes `flake8` upgrade from 4.0.1 to 6.0.0, as explained in https://github.com/Azure/azure-cli-dev-tools/pull/351#discussion_r1098244652

### CODE REVIEW

File: azdev/operations/help/refdoc/common/directives.py [hunk 1]
```diff
@@ -53,7 +53,7 @@ class CliGroupDirective(CliBaseDirective):
         Field('docsource', label='Doc Source', has_arg=False,
               names=('docsource', 'documentsource')),
         Field('deprecated', label='Deprecated', has_arg=False,
-              names=('deprecated'))
+              names=('deprecated',))
```
Comment (bebound) [inline azdev/operations/help/refdoc/common/directives.py:56]: `names` should be `Tuple[unicode, ...]`.
https://github.com/sphinx-doc/sphinx/blob/645044d7f03c7fcb4c39a8edf40aa66f6d6c2b64/sphinx/util/docfields.py#L55-L57

Why this type error never found?

File: tox.ini [hunk 2]
```diff
@@ -13,5 +13,5 @@ whitelist_externals =
 commands=
     python ./scripts/license_verify.py
     python setup.py check -r -s
-    pylint azdev --rcfile=.pylintrc -r n
+    pylint azdev --rcfile=.pylintrc -r n --load-plugins=pylint.extensions.no_self_use
```
Comment (bebound) [inline tox.ini]: Add `load-plugins` to prevent `azdev/operations/help/refdoc/common/directives.py:46:0: R0022: Useless option value for 'disable', 'no-self-use' was moved to an optional extension, see https://pylint.pycqa.org/en/latest/whatsnew/2/2.14/summary.html#removed-checkers. (useless-option-value)`

File: azdev/operations/help/refdoc/common/directives.py [hunk 3]
```diff
@@ -37,13 +37,13 @@ def handle_signature(self, sig, signode):
...
         return sig
 
-    def needs_arglist(self):  # pylint: disable=no-self-use
+    def needs_arglist(self):
         return False
 
     def add_target_and_index(self, name, sig, signode):
         signode['ids'].append(name)
 
-    def get_index_text(self, modname, name):  # pylint: disable=unused-argument, no-self-use
```
Comment (bebound) [inline azdev/operations/help/refdoc/common/directives.py:46]: Otherwise it raises `azdev/operations/help/refdoc/common/directives.py:46:0: R0022: Useless option value for 'disable', 'no-self-use' was moved to an optional extension, see https://pylint.pycqa.org/en/latest/whatsnew/2/2.14/summary.html#removed-checkers. (useless-option-value)`

File: azdev/operations/pypi.py [hunk 4]
```diff
@@ -8,7 +8,7 @@
 import re
 import sys
 
-from distutils.version import LooseVersion  # pylint:disable=import-error,no-name-in-module
+from distutils.version import LooseVersion  # pylint:disable=import-error,no-name-in-module,deprecated-module
```
Comment (bebound) [inline azdev/operations/pypi.py:11]: Temporally disable this warning.
I will create another PR to fix this like https://github.com/Azure/azure-cli/pull/17667

File: azdev/config/cli.flake8 [hunk 5]
```diff
@@ -2,17 +2,23 @@
...
+    # bare except, bad practice, to be removed in the future
+    E722,
+    # imported but unused, too many violations, to be removed in the future
+    F401,
+    # redefinition of unused, to be removed in the future
+    F811,
+    # code flow is too complex, too many violations, to be removed in the future
+    C901,
+    # line break after binary operator effect on readability is subjective
+    W504
```
Comment (bebound) [inline azdev/config/cli.flake8:18]: Fix `ValueError: Error code '#' supplied to 'ignore' option does not match '^[A-Z]{1,3}[0-9]{0,3}$'`
Flake8 does not support inline comments for any of the keys, so comments should be put in newline.
Related issue: https://github.com/PyCQA/flake8/issues/1750

Comment (bebound) [reply azdev/config/cli.flake8:18]: When `pylint==2.11.1`, it installs `mccabe` 0.6.1. `flake8` also requires `mccabe`, and only **4.0.1** meet the [version constraint](https://github.com/PyCQA/flake8/blob/82b698e09996cdde5d473e234681d8380810d7a2/setup.cfg#L42).
```
  - pylint [required: ==2.11.1, installed: 2.11.1]
    - astroid [required: >=2.8.0,<2.9, installed: 2.8.6]
      - lazy-object-proxy [required: >=1.4.0, installed: 1.9.0]
      - setuptools [required: >=20.0, installed: 63.2.0]
      - wrapt [required: >=1.11,<1.14, installed: 1.13.3]
    - isort [required: >=4.2.5,<6, installed: 5.12.0]
    - mccabe [required: >=0.6,<0.7, installed: 0.6.1]
    - platformdirs [required: >=2.2.0, installed: 2.6.2]
    - toml [required: >=0.7.1, installed: 0.10.2]
 
- flake8 [required: Any, installed: 4.0.1]
    - mccabe [required: >=0.6.0,<0.7.0, installed: 0.6.1]
    - pycodestyle [required: >=2.8.0,<2.9.0, installed: 2.8.0]
    - pyflakes [required: >=2.4.0,<2.5.0, installed: 2.4.0]
```
After upgrading PyLint 2.16.1, `mccabe` becomes [required: >=0.6,<0.8, installed: 0.7.0], and flake8 becomes **6.0.0**.

**Comment by dciborow** [comment]
@bebound , great work here!

I've used your branch as a base to upgrade pylint to 2.17.0, while also renaming some of the settings which changed after pylint 2.14 per https://github.com/PyCQA/pylint/issues/6931

Made a PR into your branch here - https://github.com/bebound/azure-cli-dev-tools/pull/1

and a fresh PR to the repo here - https://github.com/Azure/azure-cli-dev-tools/pull/359/

File: tox.ini (hunk 2 above)
Comment (jiasli) [reply tox.ini]: Will it make more sense if we remove `# pylint: disable=no-self-use` instead? Pylint apparently doesn't think `no-self-use` is important anymore: https://github.com/pylint-dev/pylint/issues/5502

File: azdev/config/cli.flake8 (hunk 5 above)
Comment (jiasli) [reply azdev/config/cli.flake8:18]: Does this issue still exist in pylint 2.17.4? https://pypi.org/project/pylint/

File: tox.ini (hunk 2 above)
Comment (bebound) [reply tox.ini]: Yes, we do this in #359

**Comment by bebound** [comment]
Close as https://github.com/Azure/azure-cli-dev-tools/pull/359 is merged
