### ISSUE TITLE
`azdev test core` fails: AttributeError: 'AssertionRewritingHook' object has no attribute 'find_spec'

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli-dev-tools#211]
Command:
```
azdev test core --discover --series
```

It fails with error:

```
______________________ HelpTest.test_help_loads ______________________ 

name = 'azure.mgmt.applicationinsights.models.web_test', path = ['d:\\cli\\env38\\lib\\site-packages\\azure\\mgmt\\applicationinsights\\models'], target = None

>   ???
E   AttributeError: 'AssertionRewritingHook' object has no attribute 'find_spec'

<frozen importlib._bootstrap>:908: AttributeError
```

This seems to be related to https://github.com/pytest-dev/pytest/issues/1888.

**Comment by jiasli** [comment]
This issue only happens on Windows with pytest 4.4.2.
```
> pip list | sls pytest

pytest                                4.4.2
pytest-forked                         1.1.3
pytest-xdist                          1.31.0
```

It is gone after upgrading pytest to 5.4.3.

```
> pip list | sls pytest

pytest                                5.4.3
pytest-forked                         1.1.3
pytest-xdist                          1.31.0
```
