### PR TITLE
Bump Pylint to 2.17 and flake8 to 6.0

### LINKED ISSUE #377: Outdated pylint breaks install
I am unable to update to the latest version in Python 3.11 due to the outdated pylint version.

```sh
(env) @dciborow_microsoft ➜ /workspaces/gpt-review/copilot (main) $ pip install azdev
Requirement already satisfied: azdev in ./env/lib/python3.11/site-packages (0.1.46)
Collecting azure-multiapi-storage (from azdev)
  Using cached azure_multiapi_storage-1.1.0-py2.py3-none-any.whl (2.8 MB)
Collecting docutils (from azdev)
  Using cached docutils-0.20.1-py3-none-any.whl (572 kB)
Collecting flake8 (from azdev)
  Using cached flake8-6.0.0-py2.py3-none-any.whl (57 kB)
Collecting gitpython (from azdev)
  Using cached GitPython-3.1.31-py3-none-any.whl (184 kB)
Collecting jinja2 (from azdev)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Requirement already satisfied: knack in ./env/lib/python3.11/site-packages (from azdev) (0.10.1)
Collecting pylint==2.11.1 (from azdev)
  Using cached pylint-2.11.1-py3-none-any.whl (392 kB)
Collecting pytest-xdist (from azdev)
  Using cached pytest_xdist-3.3.1-py3-none-any.whl (41 kB)
Collecting pytest-forked (from azdev)
  Using cached pytest_forked-1.6.0-py3-none-any.whl (4.9 kB)
Collecting pytest>=5.0.0 (from azdev)
  Using cached pytest-7.3.1-py3-none-any.whl (320 kB)
Requirement already satisfied: pyyaml in ./env/lib/python3.11/site-packages (from azdev) (6.0)
Collecting requests (from azdev)
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting sphinx==1.6.7 (from azdev)
  Using cached Sphinx-1.6.7-py2.py3-none-any.whl (1.9 MB)
Collecting tox (from azdev)
  Using cached tox-4.5.1-py3-none-any.whl (148 kB)
Collecting jsbeautifier~=1.14.7 (from azdev)
  Using cached jsbeautifier-1.14.7.tar.gz (74 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting deepdiff~=6.3.0 (from azdev)
  Using cached deepdiff-6.3.0-py3-none-any.whl (69 kB)
Collecting wheel==0.30.0 (from azdev)
  Using cached wheel-0.30.0-py2.py3-none-any.whl (49 kB)
Collecting platformdirs>=2.2.0 (from pylint==2.11.1->azdev)
  Using cached platformdirs-3.5.1-py3-none-any.whl (15 kB)
Collecting astroid<2.9,>=2.8.0 (from pylint==2.11.1->azdev)
  Using cached astroid-2.8.6-py3-none-any.whl (248 kB)
Collecting isort<6,>=4.2.5 (from pylint==2.11.1->azdev)
  Using cached isort-5.12.0-py3-none-any.whl (91 kB)
Collecting mccabe<0.7,>=0.6 (from pylint==2.11.1->azdev)
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting toml>=0.7.1 (from pylint==2.11.1->azdev)
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting six>=1.5 (from sphinx==1.6.7->azdev)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: Pygments>=2.0 in ./env/lib/python3.11/site-packages (from sphinx==1.6.7->azdev) (2.15.1)
Collecting snowballstemmer>=1.1 (from sphinx==1.6.7->azdev)
  Using cached snowballstemmer-2.2.0-py2.py3-none-any.whl (93 kB)
Collecting babel!=2.0,>=1.3 (from sphinx==1.6.7->azdev)
  Using cached Babel-2.12.1-py3-none-any.whl (10.1 MB)
Collecting alabaster<0.8,>=0.7 (from sphinx==1.6.7->azdev)
  Using cached alabaster-0.7.13-py3-none-any.whl (13 kB)
Collecting imagesize (from sphinx==1.6.7->azdev)
  Using cached imagesize-1.4.1-py2.py3-none-any.whl (8.8 kB)
Requirement already satisfied: setuptools in ./env/lib/python3.11/site-packages (from sphinx==1.6.7->azdev) (65.5.0)
Collecting sphinxcontrib-websupport (from sphinx==1.6.7->azdev)
  Using cached sphinxcontrib_websupport-1.2.4-py2.py3-none-any.whl (39 kB)
Collecting ordered-set<4.2.0,>=4.0.2 (from deepdiff~=6.3.0->azdev)
  Using cached ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->azdev)
  Using cached MarkupSafe-2.1.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (27 kB)
Collecting editorconfig>=0.12.2 (from jsbeautifier~=1.14.7->azdev)
  Using cached EditorConfig-0.12.3-py3-none-any.whl (16 kB)
Collecting iniconfig (from pytest>=5.0.0->azdev)
  Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Collecting packaging (from pytest>=5.0.0->azdev)
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting pluggy<2.0,>=0.12 (from pytest>=5.0.0->azdev)
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting charset-normalizer<4,>=2 (from requests->azdev)
  Using cached charset_normalizer-3.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (197 kB)
Collecting idna<4,>=2.5 (from requests->azdev)
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1 (from requests->azdev)
  Using cached urllib3-2.0.2-py3-none-any.whl (123 kB)
Collecting certifi>=2017.4.17 (from requests->azdev)
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting azure-common (from azure-multiapi-storage->azdev)
  Using cached azure_common-1.1.28-py2.py3-none-any.whl (14 kB)
Collecting python-dateutil (from azure-multiapi-storage->azdev)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting azure-core<2.0.0,>=1.10.0 (from azure-multiapi-storage->azdev)
  Using cached azure_core-1.26.4-py3-none-any.whl (173 kB)
Collecting msrest>=0.6.18 (from azure-multiapi-storage->azdev)
  Using cached msrest-0.7.1-py3-none-any.whl (85 kB)
Collecting cryptography>=2.1.4 (from azure-multiapi-storage->azdev)
  Using cached cryptography-40.0.2-cp36-abi3-manylinux_2_28_x86_64.whl (3.7 MB)
INFO: pip is looking at multiple versions of flake8 to determine which version is compatible with other requirements. This could take a while.
Collecting flake8 (from azdev)
  Using cached flake8-5.0.4-py2.py3-none-any.whl (61 kB)
  Using cached flake8-5.0.3-py2.py3-none-any.whl (61 kB)
  Using cached flake8-5.0.2-py2.py3-none-any.whl (61 kB)
  Using cached flake8-5.0.1-py2.py3-none-any.whl (61 kB)
  Using cached flake8-5.0.0-py2.py3-none-any.whl (61 kB)
  Using cached flake8-4.0.1-py2.py3-none-any.whl (64 kB)
Collecting pycodestyle<2.9.0,>=2.8.0 (from flake8->azdev)
  Using cached pycodestyle-2.8.0-py2.py3-none-any.whl (42 kB)
Collecting pyflakes<2.5.0,>=2.4.0 (from flake8->azdev)
  Using cached pyflakes-2.4.0-py2.py3-none-any.whl (69 kB)
Collecting gitdb<5,>=4.0.1 (from gitpython->azdev)
  Using cached gitdb-4.0.10-py3-none-any.whl (62 kB)
Requirement already satisfied: argcomplete in ./env/lib/python3.11/site-packages (from knack->azdev) (3.0.8)
Requirement already satisfied: jmespath in ./env/lib/python3.11/site-packages (from knack->azdev) (1.0.1)
Requirement already satisfied: tabulate in ./env/lib/python3.11/site-packages (from knack->azdev) (0.9.0)
Collecting py (from pytest-forked->azdev)
  Using cached py-1.11.0-py2.py3-none-any.whl (98 kB)
Collecting execnet>=1.1 (from pytest-xdist->azdev)
  Using cached execnet-1.9.0-py2.py3-none-any.whl (39 kB)
Collecting cachetools>=5.3 (from tox->azdev)
  Using cached cachetools-5.3.0-py3-none-any.whl (9.3 kB)
Collecting chardet>=5.1 (from tox->azdev)
  Using cached chardet-5.1.0-py3-none-any.whl (199 kB)
Collecting colorama>=0.4.6 (from tox->azdev)
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting filelock>=3.11 (from tox->azdev)
  Using cached filelock-3.12.0-py3-none-any.whl (10 kB)
Collecting pyproject-api>=1.5.1 (from tox->azdev)
  Using cached pyproject_api-1.5.1-py3-none-any.whl (12 kB)
Collecting virtualenv>=20.21 (from tox->azdev)
  Using cached virtualenv-20.23.0-py3-none-any.whl (3.3 MB)
Collecting lazy-object-proxy>=1.4.0 (from astroid<2.9,>=2.8.0->pylint==2.11.1->azdev)
  Using cached lazy_object_proxy-1.9.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (64 kB)
Collecting wrapt<1.14,>=1.11 (from astroid<2.9,>=2.8.0->pylint==2.11.1->azdev)
  Using cached wrapt-1.13.3.tar.gz (48 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [86 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-build-env-b59wldyc/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 81, in __getattr__
          return next(
                 ^^^^^
        File "/tmp/pip-build-env-b59wldyc/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 82, in <genexpr>
          ast.literal_eval(value)
        File "/usr/local/lib/python3.11/ast.py", line 110, in literal_eval
          return _convert(node_or_string)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/ast.py", line 109, in _convert
          return _convert_signed_num(node)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/ast.py", line 83, in _convert_signed_num
          return _convert_num(node)
                 ^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/ast.py", line 74, in _convert_num
          _raise_malformed_node(node)
        File "/usr/local/lib/python3.11/ast.py", line 71, in _raise_malformed_node
          raise ValueError(msg + f': {node!r}')
      ValueError: malformed node or string on line 2: <ast.Call object at 0x7fc3f2faba60>
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/tmp/pip-build-env-b59wldyc/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 191, in read_attr
          return getattr(StaticModule(module_name, spec), attr_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b59wldyc/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 87, in __getattr__
          raise AttributeError(f"{self.name} has no attribute {attr}") from e
      AttributeError: wrapt has no attribute __version__
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/workspaces/gpt-review/copilot/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/workspaces/gpt-review/copilot/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/workspaces/gpt-review/copilot/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b59wldyc/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-b59wldyc/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b59wldyc/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 41, in <module>
        File "/tmp/pip-build-env-b59wldyc/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b59wldyc/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/tmp/pip-build-env-b59wldyc/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 904, in parse_config_files
          setupcfg.parse_configuration(
        File "/tmp/pip-build-env-b59wldyc/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 189, in parse_configuration
          meta.parse()
        File "/tmp/pip-build-env-b59wldyc/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 500, in parse
          section_parser_method(section_options)
        File "/tmp/pip-build-env-b59wldyc/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 475, in parse_section
          self[name] = value
          ~~~~^^^^^^
        File "/tmp/pip-build-env-b59wldyc/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 293, in __setitem__
          parsed = self.parsers.get(option_name, lambda x: x)(value)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b59wldyc/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 606, in _parse_version
          return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b59wldyc/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 417, in _parse_attr
          return expand.read_attr(attr_desc, package_dir, root_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b59wldyc/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 194, in read_attr
          module = _load_spec(spec, module_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b59wldyc/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 214, in _load_spec
          spec.loader.exec_module(module)  # type: ignore
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap_external>", line 940, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/tmp/pip-install-u19mv5e6/wrapt_e1a84546efc04691ad3d735066a3100f/src/wrapt/__init__.py", line 10, in <module>
          from .decorators import (adapter_factory, AdapterFactory, decorator,
        File "/tmp/pip-install-u19mv5e6/wrapt_e1a84546efc04691ad3d735066a3100f/src/wrapt/decorators.py", line 34, in <module>
          from inspect import ismethod, isclass, formatargspec
      ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/local/lib/python3.11/inspect.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### PR DESCRIPTION
**Pull request by dciborow**
Fixes: #377  Update dependencies to become compatible with Python 3.11

This updates the previous start to this fix here - https://github.com/Azure/azure-cli-dev-tools/pull/351

Pylint and flake8 are bumped together, see https://github.com/Azure/azure-cli-dev-tools/pull/359#discussion_r1259335883

### CODE REVIEW

File: setup.py [hunk 1]
```diff
@@ -71,7 +71,7 @@
         'gitpython',
         'jinja2',
         'knack',
-        'pylint==2.11.1',
+        'pylint==2.17.0',
```
Comment (dciborow) [inline setup.py]:
```suggestion
        'pylint>2.11,<=2.17.1',
```

File: setup.py [hunk 2]
```diff
@@ -71,7 +71,7 @@
         'gitpython',
         'jinja2',
         'knack',
-        'pylint==2.11.1',
+        'pylint>2.11,<=2.17.1',
```
Comment (dciborow) [inline setup.py]:
```suggestion
        'pylint>=2.12,<=2.17.1',
```

File: azdev/operations/testtool/tests/test_profile_context.py [hunk 3]
```diff
@@ -30,4 +30,4 @@ def test_unsupported_profile(self):
     def test_raise_inner_exception(self):
         with self.assertRaises(Exception):
             with ProfileContext('latest'):
-                raise Exception('inner Exception')
+                raise Exception('inner Exception')  # pylint: disable=broad-exception-raised
```
Comment (dciborow) [inline azdev/operations/testtool/tests/test_profile_context.py]:
```suggestion
                raise Exception('inner Exception')
```

File: azdev/operations/pypi.py [hunk 4]
```diff
@@ -8,7 +8,7 @@
 import re
 import sys
 
-from distutils.version import LooseVersion  # pylint:disable=import-error,no-name-in-module
+from distutils.version import LooseVersion  # pylint:disable=import-error,no-name-in-module,deprecated-module
```
Comment (dciborow) [inline azdev/operations/pypi.py:11]:
```suggestion
from distutils.version import LooseVersion  # pylint:disable=import-error,no-name-in-module
```

File: .pylintrc [hunk 5]
```diff
@@ -10,7 +10,8 @@ disable=
     too-few-public-methods,
     too-many-arguments,
     consider-using-f-string,
-    unspecified-encoding
+    unspecified-encoding,
+    broad-exception-raised
```
Comment (dciborow) [inline .pylintrc]:
```suggestion
    broad-exception-raised,
    deprecated-module
```

File: azdev/operations/help/__init__.py [hunk 6]
```diff
@@ -300,7 +300,7 @@ def _get_whl_from_url(url, filename, tmp_dir, whl_cache=None):
     if url in whl_cache:
         return whl_cache[url]
     import requests
-    r = requests.get(url, stream=True)
+    r = requests.get(url, stream=True)  # pylint: disable=missing-timeout
```
Comment (dciborow) [inline azdev/operations/help/__init__.py]:
```suggestion
    r = requests.get(url, stream=True, timeout=10)
```

File: azdev/operations/extensions/util.py [hunk 7]
```diff
@@ -69,7 +69,7 @@ def get_whl_from_url(url, filename, tmp_dir, whl_cache=None):
     if url in whl_cache:
         return whl_cache[url]
     import requests
-    r = requests.get(url, stream=True)
+    r = requests.get(url, stream=True)  # pylint: disable=missing-timeout
```
Comment (dciborow) [inline azdev/operations/extensions/util.py]:
```suggestion
    r = requests.get(url, stream=True, timeout=10)
```

File: .pylintrc [hunk 8]
```diff
@@ -10,7 +10,10 @@ disable=
     too-few-public-methods,
     too-many-arguments,
     consider-using-f-string,
-    unspecified-encoding
+    unspecified-encoding,
+    # These rules were added in Pylint >= 2.12 and disabled to avoid making retroactively required
```
Comment (dciborow) [inline .pylintrc]:
```suggestion
    # These rules were added in Pylint >= 2.12 and are disabled to avoid making retroactively required
```

File: azdev/config/cli_pylintrc [hunk 9]
```diff
@@ -25,7 +25,11 @@ disable=
     useless-import-alias,
     useless-suppression,
     import-outside-toplevel,
-    wrong-import-order
+    wrong-import-order,
+    # These rules were added in Pylint >= 2.12 and disabled to avoid making retroactively required
```
Comment (dciborow) [inline azdev/config/cli_pylintrc]:
```suggestion
    # These rules were added in Pylint >= 2.12 and are disabled to avoid making retroactively required
```

File: azdev/config/ext_pylintrc [hunk 10]
```diff
@@ -16,7 +16,11 @@ disable=
     too-many-arguments,
     invalid-name,
     duplicate-code,
-    import-outside-toplevel
+    import-outside-toplevel,
+    # These rules were added in Pylint >= 2.12 and disabled to avoid making retroactively required
```
Comment (dciborow) [inline azdev/config/ext_pylintrc]:
```suggestion
    # These rules were added in Pylint >= 2.12 and are disabled to avoid making retroactively required
```

File: azdev/operations/help/__init__.py [hunk 11]
```diff
@@ -300,7 +300,7 @@ def _get_whl_from_url(url, filename, tmp_dir, whl_cache=None):
     if url in whl_cache:
         return whl_cache[url]
     import requests
-    r = requests.get(url, stream=True)
+    r = requests.get(url, stream=True, timeout=10)
```
Comment (bebound) [inline azdev/operations/help/__init__.py]:
``` suggestion
    r = requests.get(url, stream=True)
```

`whl` file can be large, 10s might not be enough. I suggest disabling it globally.

File: setup.py [hunk 12]
```diff
@@ -71,7 +71,7 @@
         'gitpython',
         'jinja2',
         'knack',
-        'pylint==2.11.1',
+        'pylint>=2.12,<=2.17.1',
```
Comment (bebound) [inline setup.py]:
```suggestion
        'pylint>=2.12,<3',
```
Use this to make sure we are using latest 2.17 version. (2.17.4 has been released)

**Review by bebound — APPROVED** [review]

File: azdev/config/cli.flake8 [hunk 13]
```diff
@@ -2,13 +2,20 @@
...
 ignore =
-    E501,  # line too long, it is covered by pylint
-    E722,  # bare except, bad practice, to be removed in the future
-    F401,  # imported but unused, too many violations, to be removed in the future
-    F811,  # redefinition of unused, to be removed in the future
-    C901   # code flow is too complex, too many violations, to be removed in the future
-    W503   # line break before binary operator
-    W504   # line break after binary operator effect on readability is subjective
+    # line too long, it is covered by pylint
+    E501,
```
Comment (jiasli) [inline azdev/config/cli.flake8:6]: Any reason for reformatting?

File: .pylintrc [hunk 14]
```diff
@@ -10,7 +10,11 @@ disable=
     too-few-public-methods,
     too-many-arguments,
     consider-using-f-string,
-    unspecified-encoding
+    unspecified-encoding,
+    # These rules were added in Pylint >= 2.12 and are disabled to avoid making retroactively required
```
Comment (jiasli) [inline .pylintrc]: This sentence is not grammatically correct and hard to understand.

File: azdev/config/cli_pylintrc [hunk 15]
```diff
@@ -50,13 +54,13 @@ min-similarity-lines=10
...
+module-naming-style=snake_case
+const-naming-style=UPPER_CASE
+class-naming-style=PascalCase
+class-attribute-naming-style=snake_case
+attr-naming-style=snake_case
+method-naming-style=snake_case
+function-naming-style=snake_case
+argument-naming-style=snake_case
+variable-naming-style=snake_case
+inlinevar-naming-style=snake_case
```
Comment (jiasli) [inline azdev/config/cli_pylintrc]: Any reason for the name change?

File: azdev/operations/help/refdoc/common/directives.py [hunk 16]
```diff
@@ -63,23 +63,23 @@ class CliCommandDirective(CliBaseDirective):
...
+              names=('deprecated',))
     ])
 
 
 class CliArgumentDirective(CliBaseDirective):
     doc_field_types = copy.copy(_CLI_FIELD_TYPES)
     doc_field_types.extend([
         Field('required', label='Required', has_arg=False,
-              names=('required')),
+              names=('required',)),
```
Comment (jiasli) [inline azdev/operations/help/refdoc/common/directives.py:74]: This changes the semantics of the code. Better to confirm if it is required or works as expected.

File: azdev/config/cli.flake8 (hunk 13 above)
Comment (bebound) [reply azdev/config/cli.flake8:6]: Because flake8 upgrade to 6.0. Flake8 6.0 does not support inline comments for any of the keys, so comments should be put in newline.
Use this to prevent `ValueError: Error code '#' supplied to 'ignore' option does not match '^[A-Z]{1,3}[0-9]{0,3}$'`

Related issue: https://github.com/PyCQA/flake8/issues/1750 https://github.com/Azure/azure-cli/pull/25370

File: azdev/operations/help/refdoc/common/directives.py (hunk 16 above)
Comment (bebound) [reply azdev/operations/help/refdoc/common/directives.py:74]: `names` should be `Tuple[unicode, ...]`.
https://github.com/sphinx-doc/sphinx/blob/645044d7f03c7fcb4c39a8edf40aa66f6d6c2b64/sphinx/util/docfields.py#L55-L57

Why is this type error never found?

File: azdev/operations/help/refdoc/common/directives.py [hunk 17]
```diff
@@ -37,13 +37,13 @@ def handle_signature(self, sig, signode):
...
         return sig
 
-    def needs_arglist(self):  # pylint: disable=no-self-use
+    def needs_arglist(self):
         return False
 
     def add_target_and_index(self, name, sig, signode):
         signode['ids'].append(name)
 
-    def get_index_text(self, modname, name):  # pylint: disable=unused-argument, no-self-use
```
Comment (bebound) [inline azdev/operations/help/refdoc/common/directives.py:46]: Otherwise it raises `azdev/operations/help/refdoc/common/directives.py:46:0: R0022: Useless option value for 'disable', 'no-self-use' was moved to an optional extension, see https://pylint.pycqa.org/en/latest/whatsnew/2/2.14/summary.html#removed-checkers. (useless-option-value)`

File: azdev/config/cli.flake8 (hunk 13 above)
Comment (bebound) [reply azdev/config/cli.flake8:6]: When `pylint==2.11.1`, it installs `mccabe` 0.6.1. `flake8` also requires `mccabe`, and only **4.0.1** meet the [version constraint](https://github.com/PyCQA/flake8/blob/82b698e09996cdde5d473e234681d8380810d7a2/setup.cfg#L42).
```
  - pylint [required: ==2.11.1, installed: 2.11.1]
    - astroid [required: >=2.8.0,<2.9, installed: 2.8.6]
      - lazy-object-proxy [required: >=1.4.0, installed: 1.9.0]
      - setuptools [required: >=20.0, installed: 63.2.0]
      - wrapt [required: >=1.11,<1.14, installed: 1.13.3]
    - isort [required: >=4.2.5,<6, installed: 5.12.0]
    - mccabe [required: >=0.6,<0.7, installed: 0.6.1]
    - platformdirs [required: >=2.2.0, installed: 2.6.2]
    - toml [required: >=0.7.1, installed: 0.10.2]
 
- flake8 [required: Any, installed: 4.0.1]
    - mccabe [required: >=0.6.0,<0.7.0, installed: 0.6.1]
    - pycodestyle [required: >=2.8.0,<2.9.0, installed: 2.8.0]
    - pyflakes [required: >=2.4.0,<2.5.0, installed: 2.4.0]
```
After upgrading PyLint 2.7, `mccabe` becomes [required: >=0.6,<0.8, installed: 0.7.0], and flake8 becomes **6.0.0**.

File: azdev/config/cli_pylintrc (hunk 15 above)
Comment (bebound) [reply azdev/config/cli_pylintrc]: I think this is a incompatibility introduced by pylint 2.14
> Several occurrences of E0015: Unrecognized option found on the config file: 
function-name-hint, variable-name-hint, const-name-hint, attr-name-hint, argument-name-hint, class-attribute-name-hint, inlinevar-name-hint, class-name-hint, module-name-hint, method-name-hint - This is where the incompatibility is: The old option names are rejected by pylint 2.14, and the new option names are rejected by older pylint versions.

Ref: https://github.com/pylint-dev/pylint/issues/6931

File: azdev/operations/help/refdoc/common/directives.py (hunk 16 above)
Comment (bebound) [reply azdev/operations/help/refdoc/common/directives.py:74]: I comfirm this is a typo, as next line it becomes a tuple:
https://github.com/Azure/azure-cli-dev-tools/blob/cabbb3ef6eeb398a5100f14c19d5cc3f4a8ac840/azdev/operations/help/refdoc/common/directives.py#L75-L76

**Review by wangzelin007 — APPROVED** [review]

File: .pylintrc [hunk 18]
```diff
@@ -10,7 +10,11 @@ disable=
     too-few-public-methods,
     too-many-arguments,
     consider-using-f-string,
-    unspecified-encoding
+    unspecified-encoding,
+    # These rules were added in Pylint >= 2.12, disable them to avoid making retroactive change
+    broad-exception-raised,
+    deprecated-module,
```
Comment (bebound) [inline .pylintrc]: `deprecated-module` is quite useful and there is a few errors.
I prefer to enable it by default.

File: azdev/config/cli.flake8 (hunk 13 above)
Comment (jiasli) [reply azdev/config/cli.flake8:6]: Does this issue still exist in pylint 2.17.4? https://pypi.org/project/pylint/

File: azdev/config/cli_pylintrc [hunk 19]
```diff
@@ -50,13 +53,13 @@ min-similarity-lines=10
 # The invalid-name checker must be **enabled** for these hints to be used.
 include-naming-hint=yes
 
-module-name-hint=lowercase (keep short; underscores are discouraged)
```
Comment (jiasli) [inline azdev/config/cli_pylintrc:53]: I am actually curious how `(keep short; underscores are discouraged)` works.

File: azdev/config/cli.flake8 (hunk 13 above)
Comment (bebound) [reply azdev/config/cli.flake8:6]: When run `azdev style`, it uses `pylintrc` and `.flake8` in CLI/Extension repo folder. If the files do not exist, it use `cli.xxxx` or `ext.xxx` in `azdev config` folder.
CLI's `.flake8` is updated in https://github.com/Azure/azure-cli/pull/25370.

File: azdev/config/cli_pylintrc (hunk 15 above)
Comment (jiasli) [reply azdev/config/cli_pylintrc]: I saw the document has been moved to https://pylint.pycqa.org/en/v2.17.4/user_guide/messages/convention/invalid-name.html#predefined-naming-styles

File: azdev/operations/help/refdoc/common/directives.py (hunk 17 above)
Comment (jiasli) [reply azdev/operations/help/refdoc/common/directives.py:46]: Pylint apparently doesn't think `no-self-use` is important anymore: https://github.com/pylint-dev/pylint/issues/5502

File: azdev/config/cli_pylintrc (hunk 15 above)
Comment (bebound) [reply azdev/config/cli_pylintrc]: After further investigation, these naming-style config can be removed.
1. They are nearly the same as default value.
2. `invalid-name` rule is disabled, these configurations make no sense.
3. `cli_pylintrc` hardly take effect as CLI has its own `pylintrc`.

I've removed them in CLI.
https://github.com/Azure/azure-cli/pull/26685#discussion_r1230661713

File: azdev/config/cli_pylintrc (hunk 19 above)
Comment (bebound) [reply azdev/config/cli_pylintrc:53]: This hint is shown in the `invalid-name` error message. For example:
`demo/demo.py:19:0: C0103: Class name "aa" doesn't conform to '{invalid-classname-hint}' pattern ('[_]{0,2}[A-Z]{1}[A-Za-z0-9]{0,30}$' pattern) (invalid-name)`

I've removed all xxx-hint settings. See  https://github.com/Azure/azure-cli/pull/26685#discussion_r1230661713 and https://github.com/Azure/azure-cli-dev-tools/pull/359#discussion_r1262146487

**Review by jiasli — APPROVED** [review]
